sudo: false
language: node_js
node_js: stable
stages:
  - lint
  - test
jobs:
  include:
    - stage: lint
      name: "Lint JS"
      script: npm run lint
    - stage: test
      name: "Unit tests"
      script: npm run test:js
      after_success: npm run coverage
