sudo: false
language: node_js
node_js: stable
stages:
  - greenkeeper
  - lint
  - test
jobs:
  include:
    - stage: greenkeeper
      if: branch =~ /^greenkeeper.*$/
      before_install: npm i -g greenkeeper-lockfile
      install: npm i
      script:
        - greenkeeper-lockfile-update
        - greenkeeper-lockfile-upload
    - stage: lint
      name: "Lint JS"
      script: npm run lint
    - stage: test
      name: "Unit tests"
      after_success: npm run coverage
